config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :product_notes

  resources :user_notes

  resources :user_feedback_notes

  resources :product_feedback_notes

  resources :feedbacks

  resources :products

end

app/models/user_feedback_note.rb
class UserFeedbackNote < ActiveRecord::Base
end

app/controllers/user_feedback_notes_controller.rb
class UserFeedbackNotesController < ApplicationController
  before_action :set_user_feedback_note, only: [:show, :edit, :update, :destroy]

  # GET /user_feedback_notes
  # GET /user_feedback_notes.json
  def index
    @user_feedback_notes = UserFeedbackNote.all
  end

  # GET /user_feedback_notes/1
  # GET /user_feedback_notes/1.json
  def show
  end

  # GET /user_feedback_notes/new
  def new
    @user_feedback_note = UserFeedbackNote.new
  end

  # GET /user_feedback_notes/1/edit
  def edit
  end

  # POST /user_feedback_notes
  # POST /user_feedback_notes.json
  def create
    @user_feedback_note = UserFeedbackNote.new(user_feedback_note_params)

    respond_to do |format|
      if @user_feedback_note.save
        format.html { redirect_to @user_feedback_note, notice: 'User feedback note was successfully created.' }
        format.json { render :show, status: :created, location: @user_feedback_note }
      else
        format.html { render :new }
        format.json { render json: @user_feedback_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_feedback_notes/1
  # PATCH/PUT /user_feedback_notes/1.json
  def update
    respond_to do |format|
      if @user_feedback_note.update(user_feedback_note_params)
        format.html { redirect_to @user_feedback_note, notice: 'User feedback note was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_feedback_note }
      else
        format.html { render :edit }
        format.json { render json: @user_feedback_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_feedback_notes/1
  # DELETE /user_feedback_notes/1.json
  def destroy
    @user_feedback_note.destroy
    respond_to do |format|
      format.html { redirect_to user_feedback_notes_url, notice: 'User feedback note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_feedback_note
      @user_feedback_note = UserFeedbackNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_feedback_note_params
      params.require(:user_feedback_note).permit(:user_id, :feedback_id, :content)
    end
end

app/helpers/user_feedback_notes_helper.rb
module UserFeedbackNotesHelper
end

app/views/user_feedback_notes/_form.html.erb
<%= form_for(@user_feedback_note) do |f| %>
  <% if @user_feedback_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_feedback_note.errors.count, "error") %> prohibited this user_feedback_note from being saved:</h2>

      <ul>
      <% @user_feedback_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :feedback_id %><br>
    <%= f.number_field :feedback_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_feedback_notes/edit.html.erb
<h1>Editing user_feedback_note</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_feedback_note %> |
<%= link_to 'Back', user_feedback_notes_path %>

app/views/user_feedback_notes/index.html.erb
<h1>Listing user_feedback_notes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Feedback</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_feedback_notes.each do |user_feedback_note| %>
      <tr>
        <td><%= user_feedback_note.user_id %></td>
        <td><%= user_feedback_note.feedback_id %></td>
        <td><%= user_feedback_note.content %></td>
        <td><%= link_to 'Show', user_feedback_note %></td>
        <td><%= link_to 'Edit', edit_user_feedback_note_path(user_feedback_note) %></td>
        <td><%= link_to 'Destroy', user_feedback_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User feedback note', new_user_feedback_note_path %>

app/views/user_feedback_notes/new.html.erb
<h1>New user_feedback_note</h1>

<%= render 'form' %>

<%= link_to 'Back', user_feedback_notes_path %>

app/views/user_feedback_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_feedback_note.user_id %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @user_feedback_note.feedback_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @user_feedback_note.content %>
</p>

<%= link_to 'Edit', edit_user_feedback_note_path(@user_feedback_note) %> |
<%= link_to 'Back', user_feedback_notes_path %>