config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :product_notes

  resources :user_notes

  resources :user_feedback_notes

  resources :product_feedback_notes

  resources :feedbacks

  resources :products

end

app/models/product_feedback_note.rb
class ProductFeedbackNote < ActiveRecord::Base
end

app/controllers/product_feedback_notes_controller.rb
class ProductFeedbackNotesController < ApplicationController
  before_action :set_product_feedback_note, only: [:show, :edit, :update, :destroy]

  # GET /product_feedback_notes
  # GET /product_feedback_notes.json
  def index
    @product_feedback_notes = ProductFeedbackNote.all
  end

  # GET /product_feedback_notes/1
  # GET /product_feedback_notes/1.json
  def show
  end

  # GET /product_feedback_notes/new
  def new
    @product_feedback_note = ProductFeedbackNote.new
  end

  # GET /product_feedback_notes/1/edit
  def edit
  end

  # POST /product_feedback_notes
  # POST /product_feedback_notes.json
  def create
    @product_feedback_note = ProductFeedbackNote.new(product_feedback_note_params)

    respond_to do |format|
      if @product_feedback_note.save
        format.html { redirect_to @product_feedback_note, notice: 'Product feedback note was successfully created.' }
        format.json { render :show, status: :created, location: @product_feedback_note }
      else
        format.html { render :new }
        format.json { render json: @product_feedback_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_feedback_notes/1
  # PATCH/PUT /product_feedback_notes/1.json
  def update
    respond_to do |format|
      if @product_feedback_note.update(product_feedback_note_params)
        format.html { redirect_to @product_feedback_note, notice: 'Product feedback note was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_feedback_note }
      else
        format.html { render :edit }
        format.json { render json: @product_feedback_note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_feedback_notes/1
  # DELETE /product_feedback_notes/1.json
  def destroy
    @product_feedback_note.destroy
    respond_to do |format|
      format.html { redirect_to product_feedback_notes_url, notice: 'Product feedback note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_feedback_note
      @product_feedback_note = ProductFeedbackNote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_feedback_note_params
      params.require(:product_feedback_note).permit(:product_id, :user_id, :feedback_id, :content)
    end
end

app/helpers/product_feedback_notes_helper.rb
module ProductFeedbackNotesHelper
end

app/views/product_feedback_notes/_form.html.erb
<%= form_for(@product_feedback_note) do |f| %>
  <% if @product_feedback_note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_feedback_note.errors.count, "error") %> prohibited this product_feedback_note from being saved:</h2>

      <ul>
      <% @product_feedback_note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :feedback_id %><br>
    <%= f.number_field :feedback_id %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_feedback_notes/edit.html.erb
<h1>Editing product_feedback_note</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_feedback_note %> |
<%= link_to 'Back', product_feedback_notes_path %>

app/views/product_feedback_notes/index.html.erb
<h1>Listing product_feedback_notes</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>User</th>
      <th>Feedback</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_feedback_notes.each do |product_feedback_note| %>
      <tr>
        <td><%= product_feedback_note.product_id %></td>
        <td><%= product_feedback_note.user_id %></td>
        <td><%= product_feedback_note.feedback_id %></td>
        <td><%= product_feedback_note.content %></td>
        <td><%= link_to 'Show', product_feedback_note %></td>
        <td><%= link_to 'Edit', edit_product_feedback_note_path(product_feedback_note) %></td>
        <td><%= link_to 'Destroy', product_feedback_note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product feedback note', new_product_feedback_note_path %>

app/views/product_feedback_notes/new.html.erb
<h1>New product_feedback_note</h1>

<%= render 'form' %>

<%= link_to 'Back', product_feedback_notes_path %>

app/views/product_feedback_notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_feedback_note.product_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @product_feedback_note.user_id %>
</p>

<p>
  <strong>Feedback:</strong>
  <%= @product_feedback_note.feedback_id %>
</p>

<p>
  <strong>Content:</strong>
  <%= @product_feedback_note.content %>
</p>

<%= link_to 'Edit', edit_product_feedback_note_path(@product_feedback_note) %> |
<%= link_to 'Back', product_feedback_notes_path %>